service: sls-phone-validation
provider:
  name: aws
  runtime: go1.x
package:
  exclude:
    - ./**
  include:
    - ./bin/**
functions:
  validatePhone:
    name: validatePhone
    handler: bin/validatePhone
    events:
      - http:
          path: validatePhone
          method: get
          request:
            parameters:
              querystrings:
                phoneNumber: true
    environment:
      NUMVERIFY_API_KEY: ${ssm:numverifyAPIKey}
resources:
  Resources:
    ApiGatewayMethodValidatephoneGet:
      Properties:
        RequestParameters:
          method.request.path.phoneNumber: true
        Integration:
          RequestParameters:
            integration.request.path.phoneNumber: method.request.path.phoneNumber
            CacheNamespace: ApiGatewayMethodValidatephoneGetCacheNS
            CacheKeyParameters:
              - method.request.path.phoneNumber
