service: sls-phone-validation
provider:
  name: aws
  runtime: go1.x
package:
  exclude:
    - ./**
  include:
    - ./bin/**
functions:
  validatePhone:
    handler: bin/validatePhone
    events:
      - http:
          path: validatePhone
          method: get
    environment:
      NUMVERIFY_API_KEY: ${ssm:numverifyAPIKey}
